site_name: Nightcore user documentation
repo_url: https://github.com/nightcore-team/nightcore-docs
repo_name: nightcore-docs

nav:
  - Документация:
    - Информация: index.md
    - Системы:
      - Кланы:
        - Общее: common/clans.md
        - Команды: commands/clans.md
        - Компоненты: components/clans.md
      - Конфигурация:
        - Команды: commands/config.md
      - Модерация:
        - Общее: common/moderation.md
        - Команды: commands/moderation.md
        - Компоненты: components/moderation.md
      - FAQ:
        - Команды: commands/faq.md
      - Форум:
        - Общее: common/forum.md
      - Мета:
        - Команды: commands/meta.md
      - Тикеты:
        - Общее: common/tickets.md
        - Команды: commands/tickets.md
        - Компоненты: components/tickets.md
      - Предложения:
        - Общее: common/proposals.md
        - Компоненты: components/proposals.md
      - Запрос ролей:
        - Общее: common/role_requests.md
        - Команды: commands/role_requests.md
        - Компоненты: components/role_requests.md
      - Приватные комнаты:
        - Общее: common/private_rooms.md
      - Билдер компонентов:
        - Команды: commands/compbuilder.md

theme:
  name: material
  logo: assets/images/nightcore-avatar.jpg
  favicon: assets/images/nightcore-avatar.jpg
  features:
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - toc.follow

  palette:
    scheme: slate
    primary: black
    accent: lime


extra_css:
  - assets/css/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true